# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=8)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(max_length=256)),
                ('url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='sponsors')),
                ('ordering', models.IntegerField(default=0)),
                ('frontpage', models.BooleanField(default=False, help_text='Display on frontpage')),
                ('partner', models.BooleanField(default=False, help_text='Display as a partner')),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtlpy.Sponsor'),
        ),
    ]
