# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_i18nflatpage_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i18nflatpage',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='i18nflatpage',
            name='listed',
            field=models.BooleanField(default=True, help_text='Display a link for this page'),
        ),
        migrations.AlterField(
            model_name='i18nflatpage',
            name='translation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.I18NFlatPage'),
        ),
    ]
